name: Continuous Deployment

on:
  push:
    branches:
      - dev

jobs:
  deployment:
    runs-on: self-hosted
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: |
          npm run build acua-backend
          npm run build code-review
      - name: Restart server applications
        run: |
          pm2 restart dev-acua-main
          pm2 restart dev-acua-code-review
