name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: self-hosted
    steps:
      - name: Checkout main branch
        run: git switch main --quiet && git pull

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build applications
        run: |
          npm run build main
          npm run build code-review
          npm run build m-telegram-bot
          npm run build m-token
          npm run build m-user
      - name: Restart server applications
        run: |
          pm2 restart acua-main
          pm2 restart acua-code-review
          pm2 restart acua-m-telegram-bot
          pm2 restart acua-m-token
          pm2 restart acua-m-user
