name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: self-hosted
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2

      - name: Install dependencies
        run: /usr/bin/node --max_semi_space_size=1 --max_old_space_size=198 /usr/bin/npm ci --cache ~/.npm --no-audit --ignore-scripts
        run: /usr/bin/node scripts/cd-install-deps

      - name: Build applications
        run: |
          npm run build main
          npm run build code-review
          npm run build telegram-bot
      - name: Restart server applications
        run: |
          pm2 restart acua-main
          pm2 restart acua-code-review
          pm2 restart acua-telegram-bot
