name: Continuous Deployment

on:
  push:
    branches:
      - dev

jobs:
  deployment:
    runs-on: self-hosted
    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v3
        with:
          ref: 'dev'
      - name: Install dependencies
        run: npm ci
      - name: Build applications
        run: |
          npm run build main
          npm run build code-review
      - name: Restart server applications
        run: |
          pm2 restart dev-acua-main
          pm2 restart dev-acua-code-review
