name: Continuous Deployment

on:
  push:
    branches:
      - dev

jobs:
  deployment:
    runs-on: self-hosted
    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v3
        with:
          ref: 'dev'
      - name: Install dependencies
        run: npm ci
      - name: Build applications
        run: |
          npm run build main
          npm run build code-review
          npm run build m-telegram-bot
          npm run build m-token
          npm run build m-user
      - name: Setup environment
        run: |
          cp ~/envs/3000/.env dist/apps/main/.env
          cp ~/envs/3001/.env dist/apps/code-review/.env
          cp ~/envs/5001/.env dist/apps/m-token/.env
          cp ~/envs/5002/.env dist/apps/m-user/.env
          cp ~/envs/5003/.env dist/apps/m-telegram-bot/.env
      - name: Setup SSL
        run: |
          cp ~/cert/certificate.crt dist/apps/main/certificate.crt
          cp ~/cert/private.key dist/apps/main/private.key
          cp ~/cert/certificate.crt dist/apps/code-review/certificate.crt
          cp ~/cert/private.key dist/apps/code-review/private.key
      - name: Restart server applications
        run: |
          pm2 restart dev-acua-main
          pm2 restart dev-acua-code-review
          pm2 restart dev-acua-m-telegram-bot
          pm2 restart dev-acua-m-token
          pm2 restart dev-acua-m-user
