name: Continuous Deployment

on:
  push:
    branches:
      - dev

jobs:
  deployment:
    runs-on: self-hosted
    steps:
      - name: Checkout dev branch
        run: git checkout dev && git pull

      - name: Build applications
        run: |
          npm run build main
          npm run build code-review
          npm run build telegram-bot
      - name: Restart server applications
        run: |
          pm2 restart dev-acua-main
          pm2 restart dev-acua-code-review
          pm2 restart dev-acua-telegram-bot
