name: Continuous Integration

on:
  pull_request:
    branches: [ main, dev ]

jobs:
  merge_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Test application
        run: npm test acua-backend
        run: npm test code-review

      - name: Build application
        run: npm run build acua-backend
        run: npm run build code-review
