name: Continuous Integration

on:
  pull_request:
    branches: [ main, dev ]

jobs:
  merge_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Test applications
        run: |
          npm test acua-backend
          npm test code-review

      - name: Build applications
        run: |
          npm run build acua-backend
          npm run build code-review
