name: Continuous Integration

on:
  pull_request:
    branches: [ main, dev ]

jobs:
  merge_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Test applications
        run: |
          npm test main
          npm test code-review
          npm test telegram-bot
          npm test m-token
          npm test m-user

      - name: Build applications
        run: |
          npm run build main
          npm run build code-review
          npm run build telegram-bot
          npm run build m-token
          npm run build m-user
